version: '3.8'

services:
  db:
    image: postgres:15.3
    volumes:
      - app_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    command: uvicorn delvify.main:ms --host 0.0.0.0 --port 8000
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - 8000

volumes:
  app_db:
