version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    command: uvicorn delvify.main:ms --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - 8000
