name: PR checks

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.5.1
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --with lint
      - name: Test with flake8
        run: |
          python -m flake8 delvify
      - name: Test with black
        run: |
          python -m black --check delvify
      - name: Test with mypy
        run: |
          python -m mypy delvify


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.5.1
          poetry config virtualenvs.create false
          poetry self add poetry-dotenv-plugin
          poetry install --no-interaction --no-ansi --with test

      - name: Test with pytest
        run: |
          poetry run pytest
